import dbconnect from "@/lib/db";
import Footware from "@/models/Footware"; // Adjust path to where your schema is

const data = [
	{
		name: "Urban Stride Sneaker",
		slug: "urban-stride-sneaker",
		description: "A sleek white and grey modern sneaker with leather texture details, perfect for everyday streetwear.",
		gender: "Men",
		category: "Sneakers",
		price: 120.0,
		discountPrice: 99.99,
		images: [
			{ url: "https://placehold.co/600x600/png", altText: "Urban Stride Sneaker Front View", isPrimary: true },
			{ url: "https://placehold.co/600x600/png", altText: "Urban Stride Sneaker Side View", isPrimary: false },
		],
		variants: [
			{ size: 8, stock: 15, sku: "URB-STR-M-08" },
			{ size: 9, stock: 22, sku: "URB-STR-M-09" },
			{ size: 10, stock: 0, sku: "URB-STR-M-10" },
		],
		isActive: true,
	},
	{
		name: "Midnight Velvet Heels",
		slug: "midnight-velvet-heels",
		description: "Elegant stiletto heels featuring a soft velvet finish. Perfect for evening wear.",
		gender: "Women",
		category: "Heels",
		price: 150.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Midnight Velvet Heels Main", isPrimary: true }],
		variants: [
			{ size: 6, stock: 5, sku: "MID-VEL-W-06" },
			{ size: 7, stock: 12, sku: "MID-VEL-W-07" },
			{ size: 8, stock: 8, sku: "MID-VEL-W-08" },
		],
		isActive: true,
	},
	{
		name: "Trailblazer Hiking Boots",
		slug: "trailblazer-hiking-boots",
		description: "Rugged, waterproof hiking boots designed for all-terrain adventures.",
		gender: "Unisex",
		category: "Boots",
		price: 185.0,
		discountPrice: 160.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Trailblazer Boots Side", isPrimary: true }],
		variants: [
			{ size: 8, stock: 30, sku: "TRL-BLZ-U-08" },
			{ size: 9, stock: 45, sku: "TRL-BLZ-U-09" },
			{ size: 10, stock: 20, sku: "TRL-BLZ-U-10" },
			{ size: 11, stock: 10, sku: "TRL-BLZ-U-11" },
		],
		isActive: true,
	},
	{
		name: "Kids Light-Up Dashers",
		slug: "kids-light-up-dashers",
		description: "Fun and playful sneakers that light up with every step. Easy velcro straps.",
		gender: "Kids",
		category: "Sneakers",
		price: 45.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Light-up Dashers Blue", isPrimary: true }],
		variants: [
			{ size: 1, stock: 15, sku: "KID-LIT-01" },
			{ size: 2, stock: 18, sku: "KID-LIT-02" },
			{ size: 3, stock: 25, sku: "KID-LIT-03" },
		],
		isActive: true,
	},
	{
		name: "Classic Office Oxfords",
		slug: "classic-office-oxfords",
		description: "Premium genuine leather oxfords for a sharp, professional look.",
		gender: "Men",
		category: "Oxfords",
		price: 140.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Leather Oxfords Top", isPrimary: true }],
		variants: [
			{ size: 9, stock: 12, sku: "OXF-CLS-M-09" },
			{ size: 10, stock: 14, sku: "OXF-CLS-M-10" },
			{ size: 11, stock: 5, sku: "OXF-CLS-M-11" },
		],
		isActive: true,
	},
	{
		name: "Summer Breeze Sandals",
		slug: "summer-breeze-sandals",
		description: "Lightweight and breathable strappy sandals ideal for beach days and casual summer outings.",
		gender: "Women",
		category: "Sandals",
		price: 65.0,
		discountPrice: 50.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Summer Breeze Sandals", isPrimary: true }],
		variants: [
			{ size: 6, stock: 40, sku: "SND-SUM-W-06" },
			{ size: 7, stock: 55, sku: "SND-SUM-W-07" },
			{ size: 8, stock: 30, sku: "SND-SUM-W-08" },
		],
		isActive: true,
	},
	{
		name: "Cloud Comfort Runners",
		slug: "cloud-comfort-runners",
		description: "High-performance running shoes with extreme cushioning for long-distance runs.",
		gender: "Unisex",
		category: "Sneakers",
		price: 160.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Cloud Runners Profile", isPrimary: true }],
		variants: [
			{ size: 7, stock: 15, sku: "RUN-CLD-U-07" },
			{ size: 8, stock: 25, sku: "RUN-CLD-U-08" },
			{ size: 9, stock: 30, sku: "RUN-CLD-U-09" },
			{ size: 10, stock: 10, sku: "RUN-CLD-U-10" },
		],
		isActive: true,
	},
	{
		name: "Chelsea Suede Boots",
		slug: "chelsea-suede-boots",
		description: "Timeless slip-on Chelsea boots in a rich brown suede finish.",
		gender: "Men",
		category: "Boots",
		price: 135.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Brown Suede Chelsea Boot", isPrimary: true }],
		variants: [
			{ size: 8, stock: 8, sku: "BTS-CHL-M-08" },
			{ size: 9, stock: 12, sku: "BTS-CHL-M-09" },
			{ size: 10, stock: 6, sku: "BTS-CHL-M-10" },
		],
		isActive: true,
	},
	{
		name: "Ballet Core Flats",
		slug: "ballet-core-flats",
		description: "Minimalist ballet flats that provide all-day comfort without sacrificing style.",
		gender: "Women",
		category: "Flats",
		price: 55.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Pink Ballet Flats", isPrimary: true }],
		variants: [
			{ size: 5, stock: 15, sku: "FLT-BAL-W-05" },
			{ size: 6, stock: 22, sku: "FLT-BAL-W-06" },
			{ size: 7, stock: 18, sku: "FLT-BAL-W-07" },
		],
		isActive: true,
	},
	{
		name: "Toddler Splash Rainboots",
		slug: "toddler-splash-rainboots",
		description: "Bright yellow rubber boots to keep tiny feet dry during puddle-jumping sessions.",
		gender: "Kids",
		category: "Boots",
		price: 35.0,
		discountPrice: 25.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Yellow Rainboots", isPrimary: true }],
		variants: [
			{ size: 3, stock: 40, sku: "KID-RNB-03" },
			{ size: 4, stock: 35, sku: "KID-RNB-04" },
		],
		isActive: true,
	},
	{
		name: "Retro Canvas High-Tops",
		slug: "retro-canvas-high-tops",
		description: "Old-school high-top sneakers made from durable organic cotton canvas.",
		gender: "Unisex",
		category: "Sneakers",
		price: 75.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Black and White High-Tops", isPrimary: true }],
		variants: [
			{ size: 6, stock: 50, sku: "SNK-RTR-U-06" },
			{ size: 7, stock: 45, sku: "SNK-RTR-U-07" },
			{ size: 8, stock: 60, sku: "SNK-RTR-U-08" },
			{ size: 9, stock: 55, sku: "SNK-RTR-U-09" },
		],
		isActive: true,
	},
	{
		name: "Penny Loafers Essential",
		slug: "penny-loafers-essential",
		description: "The ultimate smart-casual slip-on shoe, crafted from polished black leather.",
		gender: "Men",
		category: "Loafers",
		price: 115.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Black Penny Loafers", isPrimary: true }],
		variants: [
			{ size: 8, stock: 10, sku: "LOA-PEN-M-08" },
			{ size: 9, stock: 15, sku: "LOA-PEN-M-09" },
			{ size: 10, stock: 20, sku: "LOA-PEN-M-10" },
		],
		isActive: true,
	},
	{
		name: "Chunky Platform Boots",
		slug: "chunky-platform-boots",
		description: "Edgy platform boots with a 3-inch chunky heel and side zipper.",
		gender: "Women",
		category: "Boots",
		price: 130.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Black Platform Boots", isPrimary: true }],
		variants: [
			{ size: 6, stock: 12, sku: "BTS-PLT-W-06" },
			{ size: 7, stock: 25, sku: "BTS-PLT-W-07" },
			{ size: 8, stock: 14, sku: "BTS-PLT-W-08" },
		],
		isActive: true,
	},
	{
		name: "Cozy Home Slippers",
		slug: "cozy-home-slippers",
		description: "Fleece-lined indoor slippers to keep your feet warm during winter.",
		gender: "Unisex",
		category: "Slippers",
		price: 30.0,
		discountPrice: 19.99,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Grey Fleece Slippers", isPrimary: true }],
		variants: [
			{ size: 7, stock: 100, sku: "SLP-CZY-U-07" },
			{ size: 9, stock: 120, sku: "SLP-CZY-U-09" },
			{ size: 11, stock: 80, sku: "SLP-CZY-U-11" },
		],
		isActive: true,
	},
	{
		name: "Kids Turf Soccer Cleats",
		slug: "kids-turf-soccer-cleats",
		description: "Durable soccer cleats designed for youth leagues and artificial turf.",
		gender: "Kids",
		category: "Athletic",
		price: 55.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Neon Green Soccer Cleats", isPrimary: true }],
		variants: [
			{ size: 4, stock: 30, sku: "KID-SOC-04" },
			{ size: 5, stock: 35, sku: "KID-SOC-05" },
		],
		isActive: true,
	},
	{
		name: "Breathable Mesh Slip-ons",
		slug: "breathable-mesh-slip-ons",
		description: "Ultra-lightweight slip-on walking shoes with a breathable mesh upper.",
		gender: "Men",
		category: "Sneakers",
		price: 85.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Navy Mesh Slip-on", isPrimary: true }],
		variants: [
			{ size: 9, stock: 40, sku: "SNK-MSH-M-09" },
			{ size: 10, stock: 45, sku: "SNK-MSH-M-10" },
			{ size: 11, stock: 20, sku: "SNK-MSH-M-11" },
		],
		isActive: true,
	},
	{
		name: "Ankle Strap Espadrilles",
		slug: "ankle-strap-espadrilles",
		description: "Classic summer wedges with an ankle tie and woven jute sole.",
		gender: "Women",
		category: "Wedges",
		price: 95.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Beige Espadrille Wedges", isPrimary: true }],
		variants: [
			{ size: 6, stock: 20, sku: "WDG-ESP-W-06" },
			{ size: 7, stock: 25, sku: "WDG-ESP-W-07" },
			{ size: 8, stock: 10, sku: "WDG-ESP-W-08" },
		],
		isActive: true,
	},
	{
		name: "Professional Chef Clogs",
		slug: "professional-chef-clogs",
		description: "Slip-resistant, easy-to-clean clogs designed for culinary professionals.",
		gender: "Unisex",
		category: "Workwear",
		price: 70.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Black Chef Clogs", isPrimary: true }],
		variants: [
			{ size: 8, stock: 60, sku: "CLG-CHF-U-08" },
			{ size: 9, stock: 55, sku: "CLG-CHF-U-09" },
			{ size: 10, stock: 40, sku: "CLG-CHF-U-10" },
			{ size: 11, stock: 25, sku: "CLG-CHF-U-11" },
		],
		isActive: true,
	},
	{
		name: "Winter Snow Muckers",
		slug: "winter-snow-muckers",
		description: "Insulated and fully waterproof boots for deep snow and extreme cold.",
		gender: "Men",
		category: "Boots",
		price: 160.0,
		discountPrice: 125.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Tall Winter Snow Boots", isPrimary: true }],
		variants: [
			{ size: 9, stock: 15, sku: "BTS-SNW-M-09" },
			{ size: 10, stock: 10, sku: "BTS-SNW-M-10" },
			{ size: 12, stock: 5, sku: "BTS-SNW-M-12" },
		],
		isActive: false,
	},
	{
		name: "Crystal Embellished Pumps",
		slug: "crystal-embellished-pumps",
		description: "Show-stopping party pumps adorned with hand-placed rhinestones.",
		gender: "Women",
		category: "Heels",
		price: 220.0,
		images: [{ url: "https://placehold.co/600x600/png", altText: "Silver Crystal Pumps", isPrimary: true }],
		variants: [
			{ size: 5, stock: 4, sku: "PMP-CRY-W-05" },
			{ size: 6, stock: 6, sku: "PMP-CRY-W-06" },
			{ size: 7, stock: 2, sku: "PMP-CRY-W-07" },
		],
		isActive: true,
	},
];

export default async function seedData() {
	await dbconnect();

	// Clear out the old data (optional, be careful in production!)
	await Footware.deleteMany({});

	// Insert the 20 sample items
	await Footware.insertMany(data);

	console.log("Database seeded successfully!");
}
